language: node_js
node_js:
  - 7
script:
  - node_modules/.bin/sake build
  - node_modules/.bin/sake test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
